### ISSUE TITLE
typo, chap01, Validation

### ISSUE THREAD

**Issue by rpivo** [AllenDowney/ThinkStats#2]
Is:
> The table indicates that there are 4449 cases where this variable in inapplicable.

Maybe should be:
> The table indicates that there are 4449 cases where this variable is (in?) inapplicable.

<hr />

Is:
> The values 97, 98, and 99 represent case where the birth weight is unknown.

Maybe should be:
> The values 97, 98, and 99 represent cases where the birth weight is unknown.

**Comment by AllenDowney** [comment]
Fixed. Thank you!
